print("================================")
print("   PRÁCTICA SWARM BOTS")
print("================================")
print("")
print("Nombre del proyecto: Swarm Bots")
print("Día de práctica: 1")
print("Estado: ¡Aprendiendo!")
print("")
print("Objetivos:")
print("1. Dominar Python")
print("2. Crear enjambres de robots")
print("3. Generar reportes ISO")
print("")
print("================================")
print("¡Vamos por el Día 2!")