print("=== SWARM BOTS PROJECT ===")
print("Día 1: Primer script funcionando")
print("")
print("Hola Fernando, esto es Python!")
print("")
print("=== MI PRÁCTICA DEL DÍA 1 ===")
print("Estoy aprendiendo Python")
print("Para construir Swarm Bots")
print("¡Y voy por más!")
